export const systems = [
  {
    id: "overview",
    code: "00",
    name: "Complete system",
    short: "Site map",
    summary: "Four proven generation modules connected to one monitoring and control cabinet.",
  },
  {
    id: "controller",
    code: "01",
    name: "Control cabinet",
    short: "The coordinator",
    summary: "Measures each source, applies operating limits and reports what the site is producing.",
  },
  {
    id: "sun",
    code: "02",
    name: "WELOS Sun",
    short: "Photovoltaic input",
    summary: "Grid-tied solar remains the standard generator and the commercial starting point.",
  },
  {
    id: "flow",
    code: "03",
    name: "WELOS Flow",
    short: "Micro-hydro input",
    summary: "A site-specific turbine uses verified natural head and water flow; no closed-loop pumping claim.",
  },
  {
    id: "farm",
    code: "04",
    name: "WELOS Farm",
    short: "Biogas input",
    summary: "A digester and engine-generator convert concentrated organic waste into dispatchable electricity.",
  },
  {
    id: "wind",
    code: "05",
    name: "WELOS Wind",
    short: "Measured wind input",
    summary: "A proper tower-mounted turbine is proposed only after a credible hub-height resource campaign.",
  },
];

export const parts = [
  {
    id: "enclosure",
    system: "controller",
    code: "C01",
    name: "IP-rated enclosure",
    category: "Mechanical",
    role: "Protects the control and protection hardware from dust, water and accidental contact.",
    evidence: "Concept geometry",
    status: "Requires ingress, thermal and structural validation.",
  },
  {
    id: "backplate",
    system: "controller",
    code: "C02",
    name: "Grounded backplate",
    category: "Mechanical",
    role: "Carries the DIN rail, controller, terminals and protective devices inside the cabinet.",
    evidence: "Concept geometry",
    status: "Final material and earthing path are not specified.",
  },
  {
    id: "controller-pcb",
    system: "controller",
    code: "C03",
    name: "ESP32-S3 controller PCB",
    category: "Control",
    role: "Collects telemetry, runs non-safety optimization logic and communicates with the dashboard.",
    evidence: "Reference firmware exists",
    status: "PCB shown is illustrative and has not been laid out or fabricated.",
  },
  {
    id: "energy-meter",
    system: "controller",
    code: "C04",
    name: "Revenue-grade energy meter",
    category: "Measurement",
    role: "Measures imported, exported and locally generated electrical energy for performance reporting.",
    evidence: "Required interface",
    status: "Meter model and regulatory class must be selected per market.",
  },
  {
    id: "protection",
    system: "controller",
    code: "C05",
    name: "Protection rail",
    category: "Safety",
    role: "Represents breakers, surge protection, isolation and contactors that must operate independently of cloud software.",
    evidence: "Required architecture",
    status: "Ratings and coordination require a qualified electrical engineer.",
  },
  {
    id: "communications",
    system: "controller",
    code: "C06",
    name: "Communications gateway",
    category: "Telemetry",
    role: "Provides Ethernet, Wi-Fi or cellular telemetry while keeping local control available offline.",
    evidence: "Concept interface",
    status: "Cybersecurity and carrier selection remain open work.",
  },
  {
    id: "terminal-blocks",
    system: "controller",
    code: "C07",
    name: "Field terminal blocks",
    category: "Electrical",
    role: "Separates power, sensor and communications wiring into labelled, serviceable connections.",
    evidence: "Required architecture",
    status: "Connector families depend on final voltage and sensor selection.",
  },
  {
    id: "thermal-management",
    system: "controller",
    code: "C08",
    name: "Thermal management",
    category: "Reliability",
    role: "Monitors cabinet temperature and provides filtered ventilation where passive cooling is insufficient.",
    evidence: "Concept geometry",
    status: "Needs enclosure heat-load and climate testing.",
  },
  {
    id: "sun-array",
    system: "sun",
    code: "S01",
    name: "Photovoltaic array",
    category: "Generation",
    role: "Converts sunlight into DC electricity before the certified inverter supplies site loads or the grid.",
    evidence: "Proven technology",
    status: "Size, structure and yield require a roof and shading survey.",
  },
  {
    id: "flow-turbine",
    system: "flow",
    code: "F01",
    name: "Micro-hydro turbine",
    category: "Generation",
    role: "Converts verified natural water head and flow into mechanical rotation and electricity.",
    evidence: "Proven technology",
    status: "Turbine type follows measured dry-season flow and usable head.",
  },
  {
    id: "farm-digester",
    system: "farm",
    code: "B01",
    name: "Anaerobic digester",
    category: "Fuel production",
    role: "Converts consistent manure or organic feedstock into biogas for an engine-generator.",
    evidence: "Proven technology",
    status: "Feedstock mass, gas quality, operator plan and digestate outlet must be proven.",
  },
  {
    id: "wind-turbine",
    system: "wind",
    code: "W01",
    name: "Tower-mounted turbine",
    category: "Generation",
    role: "Generates electricity at sites with professionally measured hub-height wind and suitable grid access.",
    evidence: "Proven technology",
    status: "This is not a rooftop-turbine proposal; resource measurement is mandatory.",
  },
];

export const partById = Object.fromEntries(parts.map((part) => [part.id, part]));
